name: Deployment

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.head_ref }}

      - name: Github Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "${GITHUB_CONTEXT}"

      - name: set env
        run: |
          echo "::set-env name=ENV::dev"
          ./increment-patch.sh
          echo "::set-env name=VERSION::$(git tag -l --sort=v:refname | sort -r -V | head -n 1)"

      - name: Build nginx image
        run: |
          docker build -t nginx nginx

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Tag image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          REPO="$ECR_REGISTRY/actions-test"
          docker tag nginx $REPO:$GITHUB_SHA
          docker push $REPO:$GITHUB_SHA
          docker tag nginx $REPO:$VERSION
          docker push $REPO:$VERSION
