name: Deployment

on:
  push:
    branches:
      - staging
      - production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.head_ref }}

      - name: Github Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "${GITHUB_CONTEXT}"

      - name: set env
        run: |
          echo "::set-env name=ENV::$(echo ${{ github.ref }} | grep -o "staging\|production")"
          export $VERSION=$(git tag -l --sort=v:refname | sort -r -V | head -n 1)
          echo "::set-env name=VERSION::$VERSION"
          echo "::set-env name=DEPLOYMENT_SHA::$(git rev-parse $VERSION)"
          

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Add tag for deployment image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          REPO="$ECR_REGISTRY/actions-test"
          docker pull $REPO:$DEPLOYMENT_SHA
          docker tag $REPO:$DEPLOYMENT_SHA $REPO:$ENV
          docker push $REPO:$ENV

      - name: run
        run: |
          echo "successfully finish!"
