name: Deployment

on:
  push:
    tags:
      - staging/*
      - prod/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.head_ref }}

      - name: Github Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "${GITHUB_CONTEXT}" 

      - name: set env
        env:
          REF: ${{ github.ref }}
        run: |
          echo "::set-env name=ENV::$(echo $REF | grep -o "staging\|prod")"
          echo "::set-env name=VERSION::$(echo "refs/tags/staging/v3" | sed -e  "s#.*/##g")"

      - name: confirm env
        run: |
          echo $ENV
          echo $VERSION

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.head_ref }}

      - name: Github Context
        run: |
          echo "${ENV}" 
          echo "${VERSION}" 

